version: '3'
services:
  grafana:
    image: grafana/grafana:latest
    restart: unless-stopped
    volumes:
      - ./grafana/data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USERNAME}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
      - GF_USERS_ALLOW_SIGN_UP=false
    restart: unless-stopped
    ports:
      - 3000:3000
    networks:
      - monitoring
    labels:
      org.label-schema.group: "monitoring"
    links:
      - fritzbox_smarthome_exporter
      - mon_prometheus
  mon_prometheus:
    image: prom/prometheus:latest
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    depends_on:
      - fritzbox_smarthome_exporter
    ports:
      - 127.0.0.1:9090:9090
    networks:
      - monitoring
  fritzbox_smarthome_exporter:
    image: jaymedh/fritzbox_smarthome_exporter:v0.4.3
    restart: unless-stopped
    volumes:
      - ./boxcert.cer:/fritzbox.pem:ro
    command: '-url="${FRITZ_URL}" -cert=/fritzbox.pem -noverify=true'
    ports:
      - 127.0.0.1:9103:9103
    environment:
      - USERNAME=${FRITZ_USERNAME}
      - PASSWORD=${FRITZ_PASSWORD}
    networks:
      - monitoring
networks:
  monitoring:
    external: true
volumes:
  prometheus:
