{
 "title": "FRITZ!Box Smarthome",
 "description": "FRITZ!Box Smarthome exporter dashboard ",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "switch_name",
    "query": {
     "query": "label_values(fritzbox_switch_state,device_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Devices present",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(fritzbox_device_present == 1)"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 10, "w": 21, "x": 3, "y": 0 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    { "expr": "fritzbox_temperature", "legendFormat": "{{device_name}}" }
   ]
  },
  {
   "title": "Devices known",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "count(fritzbox_device_present)" }
   ]
  },
  { "title": "Switch: ${switch_name:raw}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 }, "repeat": "switch_name" },
  {
   "title": "Leistung",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": " fritzbox_power{device_name=\"${switch_name:raw}\"}"
    }
   ]
  },
  {
   "title": "Power",
   "type": "graph",
   "gridPos": { "h": 9, "w": 21, "x": 3, "y": 11 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "expr": " fritzbox_power{device_name=\"${switch_name:raw}\"}",
     "legendFormat": "{{ device_name }}"
    }
   ]
  },
  {
   "title": "Energy total",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fritzbox_energy{device_name=\"${switch_name:raw}\"}"
    }
   ]
  }
 ]
}