global:
  scrape_interval: 5s
  evaluation_interval: 5s
rule_files:
scrape_configs:
  - job_name: 'fritzbox_smarthome_exporter'
    static_configs:
      - targets: [ 'fritzbox_smarthome_exporter:9103' ]
